---
name: Release Drafter

"on":
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/release-drafter.yaml@1e108b60c7de32c4bb02ad439c9a65368f55314e  # yamllint disable-line rule:line-length
